version: '3'

services:
  cached:
    image: memcached
    ports:
        - "11311:11211"
  db:
    image: mysql
    environment:
        MYSQL_DATABASE: 'darulakram'
      # So you don't have to use root, but you can if you like
        MYSQL_USER: 'asif'
      # You can use whatever password you like
        MYSQL_PASSWORD: '4532'
      # Password for root access
        MYSQL_ROOT_PASSWORD: 'root'
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "6300:3306"
    volumes:
        - I:/docker/mysql/conf:/etc/mysql/conf.d
  web:
    build:  .
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
        - db
        - cached
    command: python manage.py runserver 0.0.0.0:8000