# Generated by Django 2.2.7 on 2019-12-03 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 23, 35, 1, 596650, tzinfo=utc)),
        ),
    ]
