# Generated by Django 2.2.7 on 2019-12-03 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191204_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 23, 37, 16, 566364, tzinfo=utc)),
        ),
    ]
