# Generated by Django 3.0 on 2019-12-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191204_0540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
